### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luojunqi011027** [bcmi/libcom#1]
![image](https://github.com/bcmi/libcom/assets/143194084/ba2ee585-af92-4d41-bde7-d4c9a21b3ff7)
请问这个怎么解决呢？

**Comment by bo-zhang-cs** [comment]
你好，libcom开发测试环境都是linux系统，某些包在windows可能找不到对应版本。可以尝试把ResolvepackageNotFound下的包从libcom.yaml中移除，再创建conda环境，之后根据运行提示通过pip安装相应的包。
