### ISSUE TITLE
Plan to release other two tasks 'viewsynthesis', 'composition' for ControlCom Model 

### ISSUE THREAD

**Issue by liuch37** [bcmi/libcom#11]
Hi, is there a plan or estimated timeline to stablize and then release other two tasks 'view synthesis' and 'composition' for ControlCom model?  Thanks!

**Comment by bo-zhang-cs** [comment]
Thanks for your interest ! Right now, we're not planning to add the other task to libcom. You can find the reasons in previous [reply](https://github.com/bcmi/libcom/issues/3#issuecomment-1810039062).

**Comment by ustcnewly** [comment]
We plan to release the code/model at https://github.com/bcmi/ControlCom-Image-Composition before 2024/03, but we may not integrate it into our libcom.
