### ISSUE TITLE
  c1xx: fatal error C1083: 无法打开源文件: “libcom/image_harmonization/source/trilinear_cpp/src/trilinear.cpp”

### ISSUE THREAD

**Issue by XUZHOUWANG** [bcmi/libcom#12]
win11:
python:3.10.11

   creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\libcom
      creating build\temp.win-amd64-cpython-310\Release\libcom\image_harmonization
      creating build\temp.win-amd64-cpython-310\Release\libcom\image_harmonization\source
      creating build\temp.win-amd64-cpython-310\Release\libcom\image_harmonization\source\trilinear_cpp
      creating build\temp.win-amd64-cpython-310\Release\libcom\image_harmonization\source\trilinear_cpp\src
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ilibcom/image_harmonization/source/trilinear_cpp/src -ID:\Python310\lib\site-packages\torch\include -ID:\Python310\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Python310\lib\site-packages\torch\include\TH -ID:\Python310\lib\site-packages\torch\include\THC -ID:\Python310\include -ID:\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tplibcom/image_harmonization/source/trilinear_cpp/src/trilinear.cpp /Fobuild\temp.win-amd64-cpython-310\Release\libcom/image_harmonization/source/trilinear_cpp/src/trilinear.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=trilinear -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
      trilinear.cpp
      c1xx: fatal error C1083: 无法打开源文件: “libcom/image_harmonization/source/trilinear_cpp/src/trilinear.cpp”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

在管理cmd中执行如下命令：pip install libcom，报上面的错误

**Comment by bo-zhang-cs** [comment]
你好，安装trilinear库相关的问题请咨询他们的[官方仓库](https://github.com/HuiZeng/Image-Adaptive-3DLUT).
