### ISSUE TITLE
阴影生成跑不通，出现TypeError: unhashable type: 'dict'的错误

### ISSUE THREAD

**Issue by weihaoxie** [bcmi/libcom#13]
![image](https://github.com/bcmi/libcom/assets/6837658/7ff74c04-c29d-4b4d-bb18-835b49a9fbde)

**Comment by bo-zhang-cs** [comment]
你好，我们在本地运行没有出现上述错误。根据[官方issue](https://github.com/huggingface/transformers/issues/26950)，可能是transformers版本问题。建议重新安装[runtime.txt](https://github.com/bcmi/libcom/blob/main/requirements/runtime.txt)中的transformers版本。

**Comment by weihaoxie** [comment]
重装runtime.txt中的transformers版本，问题解决了，感谢
