### ISSUE TITLE
Failed to produce desired output

### ISSUE THREAD

**Issue by dain5832** [bcmi/libcom#19]
Hi!
I tried to use image harmonization, but it seems like the model produces undesired output.
Could you tell me how can I improve the result?

Here's the code I executed.
`# image harmonization

PCTNet = ImageHarmonizationModel(device=3, model_type='CDTNet') # CDTNet
comp_img1  =  os.getcwd() + '/libcom/tests/source/composite/Comp1.png'
comp_mask1 = os.getcwd() + '/libcom/tests/source/composite_mask/Comp_mask1.png'
PCT_result1 = PCTNet(comp_img1, comp_mask1)
cv2.imwrite(os.getcwd()+'/libcom/temp.png', PCT_result1)`

And this is the result I got.
![image](https://github.com/bcmi/libcom/assets/62231006/ccd88ebf-e308-414a-a3cd-ef05d2b8a587)

**Comment by bo-zhang-cs** [comment]
It seems that the issue arises from not loading the pretrained model. Could you please check this?
