### ISSUE TITLE
Getting out of memory

### ISSUE THREAD

**Issue by faiq-fabtechsol** [bcmi/libcom#23]
I am following the documentation of Libcom, and I have tested the example code. My RAM is running out of memory. I am using Linux and have 16GB of RAM with a 10GB swap area. All of my RAM is being consumed along with the swap. Additionally, I have a 16GB GPU, and I am running my model on the GPU using the `.to("cuda")` command in PyTorch. However, my RAM usage continues to increase. I want to know what the minimum requirements are to run the models. Do I have insufficient resources, or am I doing something wrong? I am strictly following the documentation.

I have completed the installation as instructed in the documents and ran the example of "ControlComModel", but it didn't work.
https://libcom.readthedocs.io/en/latest/api.html

**Comment by bo-zhang-cs** [comment]
1）The memory space required for running different models varies, and it is recommended to test in an environment with 64GB of RAM or more whenever possible.
2）Try changing the ``map_location`` parameter in the ``torch.load`` function from ``cpu`` to ``cuda:0``. This may reduce memory consumption. Refer to [this link](https://pytorch.org/docs/stable/generated/torch.load.html) for more information.

**Comment by danieldimit** [comment]
@faiq-fabtechsol did you manage to get it running? I am too trying to run it on 16GB RAM and 4GB VRAM GPU. I'm trying to run the test shadoing program:

`from libcom import ShadowGenerationModel
from libcom.utils.process_image import make_image_grid
import torch
import cv2
net = ShadowGenerationModel(device=torch.device('cuda', 0), model_type='ShadowGeneration')
print('model loaded')
comp_image1 = "../tests/shadow_generation/composite/1.png"
comp_mask1 = "../tests/shadow_generation/composite_mask/1.png"
preds = net(comp_image1, comp_mask1, number=5)
grid_img  = make_image_grid([comp_image1, comp_mask1] + preds)
cv2.imwrite('../docs/_static/image/shadow_generation_result1.jpg', grid_img)
comp_image2 = "../tests/shadow_generation/composite/2.png"
comp_mask2 = "../tests/shadow_generation/composite_mask/2.png"
preds = net(comp_image2, comp_mask2, number=5)
grid_img  = make_image_grid([comp_image2, comp_mask2] + preds)
cv2.imwrite('../docs/_static/image/shadow_generation_result2.jpg', grid_img)`

But weirdly it doesn't load anything on the GPU - VRAM isn't getting occupied at all. My RAM however is overfilled and most times my computer freezes. 1 time it went though the 50 DDIM sampler but it froze after that too.
