### ISSUE TITLE
ControlCom Model other two tasks 'viewsynthesis', 'composition'

### ISSUE THREAD

**Issue by yangmingzhuo** [bcmi/libcom#3]
Greate Work! But I notice that the ControlCom has the other two tasks can be performed which is named as 'viewsynthesis', 'composition'. But they can't be performed in this libcom project even if I have changed the indicator map as (1,1) or (1,0).

**Comment by yangmingzhuo** [comment]
Notice that the ControlCom has the other two tasks can be performed which is named as 'viewsynthesis', 'composition'. But they can't be performed in this libcom project even if I have changed the indicator map as (1,1) or (1,0).

**Comment by ustcnewly** [comment]
Thanks for your attention. We only integrate relatively mature and stable functions into libcom. So this is a truncated version of ControlCom with the other two unstable functions blocked.
