### ISSUE TITLE
您好，controllable_composition生成的图像分辨率是512*512，看起来比较模糊，请问有办法生成分辨率更大或更清晰的图片吗？

### ISSUE THREAD

**Issue by wulixunhua** [bcmi/libcom#30]

**Comment by bo-zhang-cs** [comment]
你好，我觉得有三种解决思路：1）使用超分模型直接对生成图片进行上采样；2）裁剪背景图，放大前景区域，然后进行图像合成，之后将生成图resize到原始的裁剪框，粘贴到背景上。值得注意的是，这样可能会出现明显的边界效果。3）基于我们提供的[ControlCom](https://github.com/bcmi/ControlCom-Image-Composition)预训练模型在高分辨率数据上微调，需要自己生成高分辨率的成对数据。
