### ISSUE TITLE
Pip Installation Error: opencv_python==4.1.2.30: No Matching Distribution Found

### ISSUE THREAD

**Issue by mridul404** [bcmi/libcom#31]
when running: `!pip install -r libcom/requirements/runtime.txt`

Collecting albumentations==1.3.0 (from -r libcom/requirements/runtime.txt (line 1))
  Using cached albumentations-1.3.0-py3-none-any.whl.metadata (34 kB)
Collecting einops==0.3.0 (from -r libcom/requirements/runtime.txt (line 2))
  Using cached einops-0.3.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting huggingface_hub==0.13.4 (from -r libcom/requirements/runtime.txt (line 3))
  Using cached huggingface_hub-0.13.4-py3-none-any.whl.metadata (7.5 kB)
Collecting imageio==2.9.0 (from -r libcom/requirements/runtime.txt (line 4))
  Using cached imageio-2.9.0-py3-none-any.whl.metadata (2.6 kB)
Collecting mmdet==3.2.0 (from -r libcom/requirements/runtime.txt (line 5))
  Using cached mmdet-3.2.0-py3-none-any.whl.metadata (32 kB)
Collecting mmpose==1.2.0 (from -r libcom/requirements/runtime.txt (line 6))
  Using cached mmpose-1.2.0-py2.py3-none-any.whl.metadata (29 kB)
Collecting modelscope==1.9.3 (from -r libcom/requirements/runtime.txt (line 7))
  Using cached modelscope-1.9.3-py3-none-any.whl.metadata (33 kB)
Collecting omegaconf==2.3.0 (from -r libcom/requirements/runtime.txt (line 8))
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
**ERROR: Ignored the following yanked versions: 3.4.11.39
ERROR: Could not find a version that satisfies the requirement opencv_python==4.1.2.30 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72, 4.8.0.74, 4.8.0.76, 4.8.1.78, 4.9.0.80)
ERROR: No matching distribution found for opencv_python==4.1.2.30**

**Comment by bo-zhang-cs** [comment]
Let's try a few troubleshooting steps to resolve this:
1. Ensure your Python version is compatible with the version of OpenCV you're trying to install.
2. Update pip to the latest version by running pip install --upgrade pip.
3. Instead of specifying a precise version like opencv_python==4.1.2.30, try a broader constraint like opencv-python.
4. If binaries are unavailable, consider installing OpenCV from source.
