### ISSUE TITLE
阴影生成模型SGDiffusion

### ISSUE THREAD

**Issue by Echo411** [bcmi/libcom#33]
您好，我在libcom.shadow_generation这个接口的代码中发现调用的还是以前的阴影生成模型，是还没有更新为SGDiffusion吗？并且在huggingface上也没有找到SGDiffusion模型。
![image](https://github.com/bcmi/libcom/assets/60573292/ba9f6a8d-14a7-4e97-9dd1-e6b840c3b052)
![image](https://github.com/bcmi/libcom/assets/60573292/269d708d-4310-4039-b12f-659b4a2d2e68)

**Comment by bo-zhang-cs** [comment]
是的，没有更新。SGDiffusion开源地址：https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBAv2 。

**Comment by Echo411** [comment]
请问后续会更新为SGDiffusion吗？大概需要多久呢？
