### ISSUE TITLE
high CPU consumption when using PCTNet

### ISSUE THREAD

**Issue by 404Huang** [bcmi/libcom#39]
When using ImageHarmonization with
` PCTNet = ImageHarmonizationModel(device=torch.device('cuda', 0), model_type='PCTNet')`
`PCT_result = PCTNet(image, mask)`
90 CPU kernels (out of 120) are used, and it only takes 4G GPU memory. I wonder why it would happen since I have set the device to be CUDA:0. 
Do you have any idea how I could move most of the computation to GPU?

**Comment by YujieOuO** [comment]
For the inputs_preprocess function in [https://github.com/bcmi/libcom/blob/main/libcom/image_harmonization/image_harmonization.py#L88](url)
all input tensors are moved to the same GPU device for computation.
The CPU overhead may come from the functions of cv2.
