### ISSUE TITLE
ModuleNotFoundError: No module named 'trilinear'

### ISSUE THREAD

**Issue by wzh075** [bcmi/libcom#41]
我在运行测试代码时显示ModuleNotFoundError: No module named 'trilinear'，但是在清华源和官方源没有找到这个库，请问应该如何安装

**Comment by ShuaiGe01** [comment]
这篇博客可能会对你有帮助[链接](https://blog.csdn.net/qq_43646281/article/details/145948860?spm=1001.2014.3001.5501)
