### ISSUE TITLE
Libcom on x-ray image domain

### ISSUE THREAD

**Issue by pILLOW-1** [bcmi/libcom#42]
Hi, great work!
I want to use libcom on my x-ray image dataset. Specifically, given a background x-ray image, the insertion location and a foreground x-ray image. I want to insert the foreground to the corresponding location of the background image. During my experiment, I find that libcom cannot handle x-ray images well. Below are some examples(the first column is background_image, the second column is foreground_image, and the third column is the composited image):

<img width="1153" alt="scissors" src="https://github.com/user-attachments/assets/769e1994-9758-4b39-9099-0d18327a5391">
<img width="1151" alt="baton" src="https://github.com/user-attachments/assets/05c8f8e9-cc40-4eaa-82fc-106d225ba85e">
<img width="1154" alt="bullet" src="https://github.com/user-attachments/assets/8f3a487d-b8ae-40b1-8c7b-fc9a221ac231">
<img width="1151" alt="hammer" src="https://github.com/user-attachments/assets/a452ee9e-5edd-4ad0-9577-48b080063055">
<img width="1154" alt="handcuff" src="https://github.com/user-attachments/assets/1cd3035a-ec16-4456-ae80-a7c5a841d2de">
<img width="1001" alt="hammer_2" src="https://github.com/user-attachments/assets/61572c0e-763c-46ae-b0e2-2509d7093f82">

Several problems include but not limited to: object missing(1st & 3rd row), object distortion(2nd row),  extra information(4th row) and occlusion issue(5th row)
How can I improve libcom to better handle x-ray domain? To be more specific, I hope it can automatically adjust the foreground object pose, faithfully composite the object and ensure the background harmony in occlusion conditions. 
Personally, I think libcom has the potential to solve the above problems because there are indeed good cases( such as in 6th row, although the boundary is not so perfect). 
Looking forward to your answers! Thanks!

**Comment by YujieOuO** [comment]
Thanks for your attention. 
The current image composition method is heavily influenced by the domain of the training data.  For samples not seen in the training set, the model may not achieve good results. This is why the model can understand and perform reasonable composition when the foreground is a hammer, but other difficult foreground objects could not.

Here are some suggestions:
1. Replace with a clearer and higher resolution foreground image, and crop the foreground image to position the object at the center of the image. 
2. Try using the MureObjectStitchModel from our repository, which supports multiple foreground images, or try its fine-tuned version: https://github.com/bcmi/MureObjectStitch-Image-Composition

**Comment by pILLOW-1** [comment]
OK. I will try it! Thank you!
