### ISSUE TITLE
Ask about usage of this project

### ISSUE THREAD

**Issue by MATBBB0** [bcmi/libcom#8]
Could I ask whether Windows system can use this project as a tool for image composition?

**Comment by emrahoruc** [comment]
Please see the comment.
https://github.com/bcmi/libcom/issues/1#issuecomment-1793467503

**Comment by bo-zhang-cs** [comment]
Thank @emrahoruc for your reply. 

@MATBBB0 Thank you for your inquiry. We suggest running libcom on an Ubuntu system for optimal compatibility and stability. While it is possible to install libcom on other operating systems, you may need to exercise caution when handling dependency issues to prevent potential installation errors.
